BuildersCostsPerBlock = 10
DIRT_PATH = 60
ACACIA_WOOD = 75
BIRCH_WOOD = 75
DARK_OAK_WOOD = 75
JUNGLE_WOOD = 75
OAK_WOOD = 75
SPRUCE_WOOD = 75
ACACIA_LOG = 100
BIRCH_LOG = 100
DARK_OAK_LOG = 100
JUNGLE_LOG = 100
OAK_LOG = 100
SPRUCE_LOG = 100
COBWEB = 50
BRICKS = 100
BIRCH_STAIRS = 100
JUNGLE_STAIRS = 100
OAK_STAIRS = 100
SPRUCE_STAIRS = 100
RAIL = 75
OAK_FENCE = 80
STONE_BRICKS = 80
IRON_BARS = 150
GLASS_PANE = 50
OAK_FENCE_GATE = 40
NETHER_BRICK = 50
ENCHANTING_TABLE = 1550
END_STONE = 150
END_STONE_BRICKS = 200
COBBLESTONE_WALL = 40
SKELETON_SKULL = 500
HEAVY_WEIGHTED_PRESSURE_PLATE = 50
LIGHT_WEIGHTED_PRESSURE_PLATE = 50
STONE_PRESSURE_PLATE = 200
TALL_GRASS = 15
COCOA_BEANS = 20
LILY_PAD = 15
PISTON_HEAD = 120
PISTON = 120
CRAFTING_TABLE = 40
COARSE_DIRT = 50
ROSE_BUSH = 10
STONE = 30
GRASS_BLOCK = 25
DIRT = 50
COBBLESTONE = 25
LOG_2 = 100
LOG = 100
WATER = 10
SAND = 25
GRAVEL = 25
GLASS = 50
LAPIS_BLOCK = 400
DISPENSER = 40
SANDSTONE = 40
NOTE_BLOCK = 500
POWERED_RAIL = 75
DETECTOR_RAIL = 75
WEB = 50
WOOL = 20
GOLD_BLOCK = 100
IRON_BLOCK = 100
CLAY_BRICK = 100
BOOKSHELF = 100
TORCH = 10
ACACIA_STAIRS = 50
BIRCH_WOOD_STAIRS = 100
DARK_OAK_STAIRS = 50
JUNGLE_WOOD_STAIRS = 100
WOOD_STAIRS = 100
SPRUCE_WOOD_STAIRS = 100
FURNACE = 40
DOOR = 100
IRON_DOOR = 1_000
LADDER = 30
RAILS = 75
COBBLESTONE_STAIRS = 20
LEVER = 10
STONE_BUTTON = 10
ICE = 20
SNOW_BLOCK = 50
JUKEBOX = 500
ACACIA_FENCE = 60
BIRCH_FENCE = 60
DARK_OAK_FENCE = 60
JUNGLE_FENCE = 60
FENCE = 80
SPRUCE_FENCE = 60
TRAPDOOR = 80
GLOWSTONE = 75
JACK_O_LANTERN = 150
CAKE = 100
SMOOTH_BRICK = 80
IRON_FENCE = 150
THIN_GLASS = 50
ACACIA_FENCE_GATE = 100
BIRCH_FENCE_GATE = 100
DARK_OAK_FENCE_GATE = 100
JUNGLE_FENCE_GATE = 100
FENCE_GATE = 40
SPRUCE_FENCE_GATE = 100
BRICK_STAIRS = 80
NETHER_BRICK_ITEM = 50
ENCHANTMENT_TABLE = 1550
BREWING_STAND = 150
CAULDRON = 100
ENDER_STONE = 150
END_BRICKS = 200
ENDER_CHEST = 2500
TRIPWIRE_HOOK = 50
EMERALD_BLOCK = 500
BEACON = 5000
COBBLE_WALL = 40
FLOWER_POT = 10
BUTTON = 10
SKULL_ITEM = 500
ANVIL = 200
TRAPPED_CHEST = 50
IRON_PLATE = 50
GOLD_PLATE = 50
DAYLIGHT_DETECTOR = 150
REDSTONE_BLOCK = 400
HOPPER = 40
QUARTZ_BLOCK = 450
QUARTZ_STAIRS = 600
ACTIVATOR_RAIL = 75
DROPPER = 40
STAINED_GLASS_PANE = 150
SLIME_BLOCK = 500
BARRIER = 50
IRON_TRAPDOOR = 50
PRISMARINE = 200
SEA_LANTERN = 300
HAY_BLOCK = 50
CARPET = 25
CLAY = 40
TERRACOTTA = 40
COAL_BLOCK = 150
PACKED_ICE = 20
BANNER = 150
PURPUR_BLOCK = 200
PURPUR_PILLAR = 250
PURPUR_STAIRS = 175
PURPUR_SLAB = 150
CHEST = 150
SIGN = 100
STONE_PLATE = 200
LEAVES = 150
CONCRETE = 75
CONCRETE_POWDER = 90
HARD_CLAY = 250
DOUBLE_PLANT = 10
VINE = 15
COCOA = 20
FIRE = 30
BEDROCK = 400
TRIPWIRE = 40
WATER_LILY = 15
GRASS_PATH = 60
SANDSTONE_STAIRS = 50
PISTON_EXTENSION = 120
PISTON_BASE = 120
COAL_ORE = 60
WHEAT = 50
WORKBENCH = 40
CHORUS_FLOWER = 30
MOSSY_COBBLESTONE = 25