[server]
max_players = 100
description = "A Feather Server"
host = "0.0.0.0"
port = 25_565
online_mode = true

[database]
type = "mysql"
username = "root"
password = ""
database = "feather"
host = "127.0.0.1"
port = 3_306

[spawn]
spawn_on_join = true
world = "demo"
x = "7.5"
y = -24
z = "-3.5"

[player.default]
prefix = "Wanderer"
prefix_color = "<gray>"
level = 1
city_color = "<gray>"
chat_color = "<gray>"

[chat]
format = "<levelcolor><level> <prefixcolor><prefix> <namecolor><player>: <chatcolor><message>"
enabled = true

  [chat.radius]
  enabled = true
  radius = 100
  MessageWhenNobodyInRange = false

[sidebar]
enabled = true
title = "<world>"

[economy]
starting_balance = 1_000

[plots.create]
commands = [
  "rg flag <plot> -w <world> interact -g NON_MEMBERS DENY",
  "rg flag <plot> -w <world> chest-access -g NON_MEMBERS DENY",
  "rg flag <plot> -w <world> USE -g MEMBERS ALLOW",
  "rg flag <plot> -w <world> INTERACT -g MEMBERS ALLOW",
  "rg flag <plot> -w <world> PVP -g MEMBERS ALLOW"
]

[plots.inactive]
days = 30

[plots.calculate]
price_formula = "<length * <width> * 32"
