[server]
max_players = 100
description = "A Feather Server"
host = '0.0.0.0'
port = 25565
online-mode = true

[database]
type = 'mysql'
username = 'root'
password = ''
database = 'feather'
host = '127.0.0.1'
port = 3306

[spawn]
spawn_on_join = true
send_join_message = true
world = 'demo'
x = 7.5
y = -24
z = -3.5

[player]
    [player.default]
    prefix = 'Zwerver'
    prefix_color = '&7'
    level = 1
    city_color = '&7'
    chat_color = '&7'

[chat]
format = '<levelcolor><level> <prefixcolor><prefix> <namecolor><player>: <chatcolor><message>'
enabled = true
    [chat.radius]
    enabled = true
    radius = 100
    MessageWhenNobodyInRange = false

[sidebar]
enabled = true
title = '<world>'

[economy]
starting_balance = 1000

[messages]
