[server]
host = '0.0.0.0'
port = 25565

[database]
type = 'mysql'
username = 'root'
password = 'root'
database = 'feather'
host = '127.0.0.1'
port = 3306

[spawn]
world = 'world'
x = 258
y = 69
z = -98

[chat]
format = '<levelcolor><level> <prefixcolor><prefix> <namecolor><player>: <chatcolor><message>'

[sidebar]
enabled = true
title = '<world>'

[messages]
join = 'Welcome to the server, <player>!'