language = "nl"
invalid_arguments = "<red>Je hebt ongeldige argumenten opgegeven voor dit commando."
invalid_username = "<red>Deze gebruikersnaam is ongeldig."
not_online = "<red>Deze speler is niet online."
no_permission = "<red>Je hebt geen toestemming om dit commando te gebruiken."
fly_on = "<green>Vliegmodus is ingeschakeld!"
fly_off = "<red>Vliegmodus is uitgeschakeld!"

[join]
enabled = true
message = "&7<player> heeft het spel toegetreden"

[leave]
enabled = true
message = "&7<player> heeft het spel verlaten"

[join_title]
title = "<worldcolor>Welkom in"
subtitle = "<worldcolor><loadingname>"

[mtworldcmd.add]
success = "<dark_aqua>Feather is succesvol <aqua>aangezet <dark_aqua>in deze wereld!"

[banking]
frozen = "<red>Dit account is bevroren, je kan geen geld meer opnemen of storten!"

  [banking.selector]
  title = "<dark_aqua>Select the account type:"

    [banking.selector.account]
    title = "<dark_aqua>Select the account:"
    lore = "(ID: <ID>)"

    [banking.selector.accounttype]
    government = "<dark_green>Government"
    savings = "<dark_red>Savings"
    private = "<gold>Private"
    business = "<dark_aqua>Business"
    no_business_accounts = "<red>You <dark_red>don't have any <red>Business <dark_red>accounts!"
    no_savings_accounts = "<red>You <dark_red>don't have any <red>Savings <dark_red>accounts!"

  [banking.menu]
  title = "<dark_aqua>Total value: <aqua>€ <amount>"
  item_lore = "<dark_aqua>This piece of money has a %newline%<dark_aqua>value of <aqua>€ <amount><dark_aqua>."

  [banking.money]
  lore = "<red>Official Minetopia banknote!"
  insufficient_balance = "<red>There is not enough money in this account"
  is_fake_money = "<dark_red>You have counterfeit money with you! We are currently unable to accept money!"

    [banking.money.withdraw]
    inventory_full = "<red>You can't withdraw money when your inventory is full!"
    private = "<dark_aqua>You have withdrawn <aqua>€ <amount> <dark_aqua>from <aqua><account>'s <dark_aqua>account"
    savings = "<dark_aqua>You have withdrawn <aqua>€ <amount> <dark_aqua>from <aqua><account>'s <dark_aqua>savings account"
    business = "<dark_aqua>You have withdrawn <aqua>€ <amount> <dark_aqua>from <aqua><account>'s <dark_aqua>business account"
    government = "<dark_aqua>You have withdrawn <aqua>€ <amount> <dark_aqua>from <aqua><account>'s <dark_aqua>government account"

    [banking.money.deposit]
    private = "<dark_aqua>You have deposited <aqua>€ <amount> <dark_aqua>to <aqua><account>'s <dark_aqua>account"
    savings = "<dark_aqua>You have deposited <aqua>€ <amount> <dark_aqua>to <aqua><account>'s <dark_aqua>savings account"
    business = "<dark_aqua>You have deposited <aqua>€ <amount> <dark_aqua>to <aqua><account>'s <dark_aqua>business account"
    government = "<dark_aqua>You have deposited <aqua>€ <amount> <dark_aqua>to <aqua><account>'s <dark_aqua>government account"

  [banking.nobankingpermission]
  deposit = "<dark_red>You only have withdrawal rights for the account <account>! Unfortunately you cannot deposit money."

[bankaccountcmd]
id_does_not_exist = "<red>There is no bankaccount with this ID."
invalid_bankpermission = "<dark_red>ERROR: <red>Invalid bankpermission, valid permissions are <permissions>."

  [bankaccountcmd.adduser]
  success = "<dark_aqua>Successfully added player <aqua><player> <dark_aqua>to this bankaccount."
  already_added = "<red>The player <dark_red><player> <red>has already been added to this bankaccount."

[atm]
require_card = "<red>You need to hold <dark_red>a debit card <red>in your hand!"
